### ISSUE TITLE
crush server (ver. 1.10.2)

### ISSUE THREAD

**Issue by TheTestMod** [iChun/IssueTracker-Mods#48]
https://pastebin.com/dTD3b0AL

**Comment by iChun** [comment]
I'm aware of the issue. Don't use it on dedicated servers yet, I'll fix it
tomorrow.

On 12 Apr 2017 12:57 am, "TheTestMod" <notifications@github.com> wrote:

https://pastebin.com/dTD3b0AL

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iChun/IssueTracker-Mods/issues/48>, or mute the thread

**Comment by iChun** [comment]
Fixed iChunUtil 6.3.1. https://github.com/iChun/iChunUtil/commit/148b79a877736103437fb4ca90a0a6034259f6c5
