### ISSUE TITLE
[BackTools][1.10] Offhand bug

### ISSUE THREAD

**Issue by sscards55** [iChun/IssueTracker-Mods#86]
If you change your item to the off hand Backtools still renders it even though it is currently in your offhand.
![2017-04-01_15 00 27](https://cloud.githubusercontent.com/assets/5591207/24582806/7f199ed2-16ec-11e7-820f-d57edbdebd07.png)

**Comment by iChun** [comment]
😐 oh. That's why you closed the others. This repo is only for mods that
are closed source or don't have their own repositories

On 5 May 2017 12:59 pm, "sscards55" <notifications@github.com> wrote:

If you change your item to the off hand Backtools still renders it even
though it is currently in your offhand.
[image: 2017-04-01_15 00 27]
<https://cloud.githubusercontent.com/assets/5591207/24582806/7f199ed2-16ec-11e7-820f-d57edbdebd07.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iChun/IssueTracker-Mods/issues/86>, or mute the thread

**Comment by sscards55** [comment]
So I will close this one and reopen the others. I just saw that this repo had newer bugs that were closed. I thought I was suppose to post the bugs here instead.

see iChun/BackTools#2

**Comment by sscards55** [comment]
Also the Issues tab in curseforge lead to this repo

**Comment by iChun** [comment]
I should update those links. Back tools and some other mods of mine were
only recently open sourced.
